Make random color cubes for each control point
BUG: why does the left mouse button not work when
I add my cubes, but it does when just the skull
is displayed?

XTK release 10 -- 2013-02-14 16:30:17 -- http://www.goXTK.com -- @goXTK xtk.js:254
event.returnValue is deprecated. Please use the standard event.preventDefault() instead. jquery.js:3254
6
Uncaught TypeError: string is not a function xtk.js:155
w.Lh xtk.js:155
w.handleEvent xtk.js:55
Zb xtk.js:64
Rb xtk.js:66
(anonymous function) xtk.js:60